### ISSUE TITLE
Exception in thread Thread-641:

### ISSUE THREAD

**Issue by hmkim** [BD2KGenomics/toil-rnaseq#150]
Hello! Please let me about this problem.

$ toil-rnaseq run jobStore --workDir=./ --batchSystem=gridEngine

```
018-07-25 16:28:30,535 - toil.leader - INFO - Job ended successfully: 'cleanup_ids' G/y/jobGE9Y0m
INFO:toil.leader:Issued job 'process_sample' a/D/jobiS9sPP with job batch system ID: 48 and cores: 1, disk: 27.7 G, and memory: 2.0 G
2018-07-25 16:28:30,537 - toil.leader - INFO - Issued job 'process_sample' a/D/jobiS9sPP with job batch system ID: 48 and cores: 1, disk: 27.7 G, and memory: 2.0 G
Unable to run job: job rejected: the requested parallel environment "shm" does not exist
Exiting.
Exception in thread Thread-641:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/BiO/BioPeople/brandon/XenaProcessing/venv/local/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 219, in run
    activity |= self.createJobs(newJob)
  File "/BiO/BioPeople/brandon/XenaProcessing/venv/local/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 121, in createJobs
    batchJobID = self.submitJob(subLine)
  File "/BiO/BioPeople/brandon/XenaProcessing/venv/local/lib/python2.7/site-packages/toil/batchSystems/gridengine.py", line 69, in submitJob
    result = int(process.stdout.readline().strip())
ValueError: invalid literal for int() with base 10: ''
```

How can I handle this problem ? Thanks in advance!

**Comment by jvivian** [comment]
Hi @hmkim ,

This is an issue [with Toil](https://github.com/DataBiosphere/toil/issues/572)'s support of GridEngine. Unfortunately, I couldn't find exactly [what versions of GridEngine](https://toil.readthedocs.io/en/3.15.0/running/hpcEnvironments.html) Toil supports, but you can open an issue on the Toil repository or bring this up in the [Toil gitter](https://gitter.im/bd2k-genomics-toil/Lobby).  Until you reach a solution, you can run your samples in the default mode / single-machine mode. Toil's best-supported framework is Mesos if you have that option available to you.

Cheers,
John

**Comment by DailyDreaming** [comment]
Just pinning this here for now or in case this is stumbled across in the future.  This looks like an old issue that was fixed to some degree by allowing the user to specify something other than `shm` with `TOIL_GRIDENGINE_PE`:
https://github.com/DataBiosphere/toil/issues/572

**Comment by jvivian** [comment]
@DailyDreaming — Thanks for the information Lon!
