### ISSUE TITLE
Unable to install -- python incompatabilities

### ISSUE THREAD

**Issue by genec1** [BD2KGenomics/toil-rnaseq#181]
I'm unable to install toil-rnaseq on ubuntu.  It appears to require python2.7 while toil requires python3:

```
> pip install toil-rnaseq
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting toil-rnaseq
  Using cached toil-rnaseq-4.1.0.tar.gz (26 kB)
Collecting toil>=3.12.0
  Using cached toil-4.2.0.tar.gz (407 kB)
ERROR: Package 'toil' requires a different Python: 2.7.12 not in '>=3.6'
```

But python3 is incompatible with toil-rnaseq:
```
> pip3 install toil-rnaseq
Defaulting to user installation because normal site-packages is not writeable
Collecting toil-rnaseq
  Using cached toil-rnaseq-4.1.0.tar.gz (26 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i6hdn8v5/toil-rnaseq/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i6hdn8v5/toil-rnaseq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zv9sasfs
         cwd: /tmp/pip-install-i6hdn8v5/toil-rnaseq/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i6hdn8v5/toil-rnaseq/setup.py", line 12, in <module>
        install_requires=[x + y for x, y in required_versions.iteritems()],
    AttributeError: 'dict' object has no attribute 'iteritems'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by jvivian** [comment]
Hi @genec1 - thank you for the issue, it looks like I need to pin the specific version of toil that this workflow uses.

**Comment by jvivian-atreca** [comment]
@genec1 — toil version is pinned in latest release (4.1.2). Let me know if you run into any issues.
